[2023-01-04 23:29:35,086] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.delete_cluster_dataproc_task manual__2023-01-04T22:46:31.216749+00:00 [queued]>
[2023-01-04 23:29:35,095] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.delete_cluster_dataproc_task manual__2023-01-04T22:46:31.216749+00:00 [queued]>
[2023-01-04 23:29:35,095] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 23:29:35,095] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 23:29:35,096] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 23:29:35,107] {taskinstance.py:1377} INFO - Executing <Task(DataprocDeleteClusterOperator): delete_cluster_dataproc_task> on 2023-01-04 22:46:31.216749+00:00
[2023-01-04 23:29:35,115] {standard_task_runner.py:52} INFO - Started process 7274 to run task
[2023-01-04 23:29:35,120] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'delete_cluster_dataproc_task', 'manual__2023-01-04T22:46:31.216749+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpun99ffc7', '--error-file', '/tmp/tmp8ql1km2j']
[2023-01-04 23:29:35,121] {standard_task_runner.py:80} INFO - Job 29: Subtask delete_cluster_dataproc_task
[2023-01-04 23:29:35,184] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.delete_cluster_dataproc_task manual__2023-01-04T22:46:31.216749+00:00 [running]> on host e35cd2348433
[2023-01-04 23:29:35,253] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=delete_cluster_dataproc_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T22:46:31.216749+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T22:46:31.216749+00:00
[2023-01-04 23:29:35,256] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-04 23:29:35,256] {dataproc.py:816} INFO - Deleting cluster: move-data
[2023-01-04 23:30:04,221] {dataproc.py:828} INFO - Cluster deleted.
[2023-01-04 23:30:04,240] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=stock_data_pipeline_dag, task_id=delete_cluster_dataproc_task, execution_date=20230104T224631, start_date=20230104T232935, end_date=20230104T233004
[2023-01-04 23:30:04,267] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 23:30:04,293] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
