[2023-01-06 23:31:58,212] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task scheduled__2023-01-05T23:15:00+00:00 [queued]>
[2023-01-06 23:31:58,220] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task scheduled__2023-01-05T23:15:00+00:00 [queued]>
[2023-01-06 23:31:58,221] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 23:31:58,221] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-06 23:31:58,221] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 23:31:58,232] {taskinstance.py:1377} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster_dataproc_task> on 2023-01-05 23:15:00+00:00
[2023-01-06 23:31:58,240] {standard_task_runner.py:52} INFO - Started process 4558 to run task
[2023-01-06 23:31:58,245] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'create_cluster_dataproc_task', 'scheduled__2023-01-05T23:15:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpuox8uf1v', '--error-file', '/tmp/tmpdto6iaqb']
[2023-01-06 23:31:58,247] {standard_task_runner.py:80} INFO - Job 87: Subtask create_cluster_dataproc_task
[2023-01-06 23:31:58,305] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task scheduled__2023-01-05T23:15:00+00:00 [running]> on host 60ad85e83037
[2023-01-06 23:31:58,373] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=create_cluster_dataproc_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-05T23:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-05T23:15:00+00:00
[2023-01-06 23:31:58,374] {dataproc.py:590} INFO - Creating cluster: move-stock-data
[2023-01-06 23:31:58,375] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-06 23:32:00,480] {dataproc.py:602} INFO - Cluster already exists.
[2023-01-06 23:32:00,692] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=stock_data_pipeline_dag, task_id=create_cluster_dataproc_task, execution_date=20230105T231500, start_date=20230106T233158, end_date=20230106T233200
[2023-01-06 23:32:00,744] {local_task_job.py:156} INFO - Task exited with return code 0
