[2023-01-04 22:46:32,488] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task manual__2023-01-04T22:46:31.216749+00:00 [queued]>
[2023-01-04 22:46:32,496] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task manual__2023-01-04T22:46:31.216749+00:00 [queued]>
[2023-01-04 22:46:32,496] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 22:46:32,496] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 22:46:32,496] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 22:46:32,508] {taskinstance.py:1377} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster_dataproc_task> on 2023-01-04 22:46:31.216749+00:00
[2023-01-04 22:46:32,517] {standard_task_runner.py:52} INFO - Started process 4763 to run task
[2023-01-04 22:46:32,523] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'create_cluster_dataproc_task', 'manual__2023-01-04T22:46:31.216749+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpju3id528', '--error-file', '/tmp/tmpgq7pa7t0']
[2023-01-04 22:46:32,524] {standard_task_runner.py:80} INFO - Job 27: Subtask create_cluster_dataproc_task
[2023-01-04 22:46:32,583] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task manual__2023-01-04T22:46:31.216749+00:00 [running]> on host e35cd2348433
[2023-01-04 22:46:32,650] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=create_cluster_dataproc_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T22:46:31.216749+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T22:46:31.216749+00:00
[2023-01-04 22:46:32,651] {dataproc.py:590} INFO - Creating cluster: move-data
[2023-01-04 22:46:32,652] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-04 22:50:02,967] {dataproc.py:534} INFO - Cluster created.
[2023-01-04 22:50:02,996] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=stock_data_pipeline_dag, task_id=create_cluster_dataproc_task, execution_date=20230104T224631, start_date=20230104T224632, end_date=20230104T225002
[2023-01-04 22:50:03,024] {local_task_job.py:156} INFO - Task exited with return code 0
